Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main(config)
  File "train.py", line 56, in main
    optimizer = getOptimizer(config["net"]["optimizer"], model)(lr=lr)
TypeError: 'Adam' object is not callable
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main(config)
  File "train.py", line 56, in main
    optimizer = getOptimizer(config["net"]["optimizer"], model)(lr=lr)
TypeError: 'Adam' object is not callable